services:
  - type: web
    name: medical-chatbot
    runtime: docker
    plan: free 
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PINECONE_API_KEY
        sync: false  
      - key: GEMINI_API_KEY
        sync: false 
      - key: PYTHON_VERSION
        value: 3.10
    healthCheckPath: /
    autoDeploy: true
